export const ADD_QUESTION_ERROR = 'ADD_QUESTION_ERROR';
export const ADD_QUESTION_LOADING = 'ADD_QUESTION_LOADING';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';

export const DELETE_QUESTION_ERROR = 'DELETE_QUESTION_ERROR';
export const DELETE_QUESTION_LOADING = 'DELETE_QUESTION_LOADING';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';

export const EDIT_QUESTION_ERROR = 'EDIT_QUESTION_ERROR';
export const EDIT_QUESTION_LOADING = 'EDIT_QUESTION_LOADING';
export const EDIT_QUESTION_SUCCESS = 'EDIT_QUESTION_SUCCESS';

export const FETCH_QUESTIONS_ERROR = 'FETCH_QUESTIONS_ERROR';
export const FETCH_QUESTIONS_LOADING = 'FETCH_QUESTIONS_LOADING';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';

export const VIEW_QUESTION_ERROR = 'FETCH_QUESTIONS_ERROR';
export const VIEW_QUESTION_LOADING = 'FETCH_QUESTIONS_LOADING';
export const VIEW_QUESTION_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';