export const ADD_RESPONDENT_ERROR = 'ADD_RESPONDENT_ERROR';
export const ADD_RESPONDENT_LOADING = 'ADD_RESPONDENT_LOADING';
export const ADD_RESPONDENT_SUCCESS = 'ADD_RESPONDENT_SUCCESS';

export const DELETE_RESPONDENT_ERROR = 'DELETE_RESPONDENT_ERROR';
export const DELETE_RESPONDENT_LOADING = 'DELETE_RESPONDENT_LOADING';
export const DELETE_RESPONDENT_SUCCESS = 'DELETE_RESPONDENT_SUCCESS';

export const EDIT_RESPONDENT_ERROR = 'EDIT_RESPONDENT_ERROR';
export const EDIT_RESPONDENT_LOADING = 'EDIT_RESPONDENT_LOADING';
export const EDIT_RESPONDENT_SUCCESS = 'EDIT_RESPONDENT_SUCCESS';

export const FETCH_RESPONDENT_ERROR = 'FETCH_RESPONDENT_ERROR';
export const FETCH_RESPONDENT_LOADING = 'FETCH_RESPONDENT_LOADING';
export const FETCH_RESPONDENT_SUCCESS = 'FETCH_RESPONDENT_SUCCESS';

export const VIEW_RESPONDENT_ERROR = 'FETCH_RESPONDENT_ERROR';
export const VIEW_RESPONDENT_LOADING = 'FETCH_RESPONDENT_LOADING';
export const VIEW_RESPONDENT_SUCCESS = 'FETCH_RESPONDENT_SUCCESS';