export const ADD_SURVEYOR_ERROR = 'ADD_SURVEYOR_ERROR';
export const ADD_SURVEYOR_LOADING = 'ADD_SURVEYOR_LOADING';
export const ADD_SURVEYOR_SUCCESS = 'ADD_SURVEYOR_SUCCESS';

export const DELETE_SURVEYOR_ERROR = 'DELETE_SURVEYOR_ERROR';
export const DELETE_SURVEYOR_LOADING = 'DELETE_SURVEYOR_LOADING';
export const DELETE_SURVEYOR_SUCCESS = 'DELETE_SURVEYOR_SUCCESS';

export const EDIT_SURVEYOR_ERROR = 'EDIT_SURVEYOR_ERROR';
export const EDIT_SURVEYOR_LOADING = 'EDIT_SURVEYOR_LOADING';
export const EDIT_SURVEYOR_SUCCESS = 'EDIT_SURVEYOR_SUCCESS';

export const FETCH_SURVEYOR_ERROR = 'FETCH_SURVEYOR_ERROR';
export const FETCH_SURVEYOR_LOADING = 'FETCH_SURVEYOR_LOADING';
export const FETCH_SURVEYOR_SUCCESS = 'FETCH_SURVEYOR_SUCCESS';

export const VIEW_SURVEYOR_ERROR = 'FETCH_SURVEYOR_ERROR';
export const VIEW_SURVEYOR_LOADING = 'FETCH_SURVEYOR_LOADING';
export const VIEW_SURVEYOR_SUCCESS = 'FETCH_SURVEYOR_SUCCESS';