export const ADD_SURVEY_ERROR = 'ADD_SURVEY_ERROR';
export const ADD_SURVEY_LOADING = 'ADD_SURVEY_LOADING';
export const ADD_SURVEY_SUCCESS = 'ADD_SURVEY_SUCCESS';

export const DELETE_SURVEY_ERROR = 'DELETE_SURVEY_ERROR';
export const DELETE_SURVEY_LOADING = 'DELETE_SURVEY_LOADING';
export const DELETE_SURVEY_SUCCESS = 'DELETE_SURVEY_SUCCESS';

export const EDIT_SURVEY_ERROR = 'EDIT_SURVEY_ERROR';
export const EDIT_SURVEY_LOADING = 'EDIT_SURVEY_LOADING';
export const EDIT_SURVEY_SUCCESS = 'EDIT_SURVEY_SUCCESS';

export const FETCH_SURVEYS_ERROR = 'FETCH_SURVEYS_ERROR';
export const FETCH_SURVEYS_LOADING = 'FETCH_SURVEYS_LOADING';
export const FETCH_SURVEYS_SUCCESS = 'FETCH_SURVEYS_SUCCESS';

export const VIEW_SURVEY_ERROR = 'FETCH_SURVEYS_ERROR';
export const VIEW_SURVEY_LOADING = 'FETCH_SURVEYS_LOADING';
export const VIEW_SURVEY_SUCCESS = 'FETCH_SURVEYS_SUCCESS';